version: "3"
services:
    postgres:
        image: postgres:13
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: program
            POSTGRES_PASSWORD: program_password
        volumes:
            - postgresql:/var/lib/postgresql
            - ./postgres/:/docker-entrypoint-initdb.d/
        ports:
            - 5432:5432
        networks:
            - internal

    librarysystem:
        build:
            dockerfile: ./v4/src/LibrarySystem/LibrarySystem/Dockerfile
        container_name: librarysystem
        restart: always
        environment:
            SERVICE_HOST: librarysystem
            SERVICE_PORT: 8080
            LIBRARY_SERVICE_HOST: library
            LIBRARY_SERVICE_PORT: 8060
            RESERVATION_SERVICE_HOST: reservation
            RESERVATION_SERVICE_PORT: 8070
            RATING_SERVICE_HOST: rating
            RATING_SERVICE_PORT: 8050
        ports:
            - 8080:8080
        networks:
            - internal

    library:
        build:
            dockerfile: ./v4/src/LibrarySystem/Library/Dockerfile
        container_name: library    
        restart: always
        environment:
            SERVICE_HOST: library
            SERVICE_PORT: 8060
            DB_HOST: postgres
        ports:
            - 8060:8060
        networks:
            - internal

    reservation:
        build:
            dockerfile: ./v4/src/LibrarySystem/Reservation/Dockerfile
        container_name: reservation
        restart: always
        environment:
            SERVICE_HOST: reservation
            SERVICE_PORT: 8070
            DB_HOST: postgres
        ports:
            - 8070:8070
        networks:
            - internal

    rating:
        build:
            dockerfile: ./v4/src/LibrarySystem/Rating/Dockerfile
        container_name: rating
        restart: always
        environment:
            SERVICE_HOST: rating
            SERVICE_PORT: 8050
            DB_HOST: postgres
        ports:
            - 8050:8050
        networks:
            - internal

volumes:
    postgresql:

networks:
    internal: